### PR TITLE
Add new input `pr_title_on_protected `

### PR DESCRIPTION
**Pull request by MrChocolatine**
### What does it do?

- Add a new input the Action can consume: `pr_title`
  This allow users to customise the title of the PR that will be created when the branch is protected.

- Fix a few things in the `README`

### Why is it needed?

For more flexibility.

### CODE REVIEW

**Comment by akhilmhdh** [comment]
@MrChocolatine Awesome. But I do have some suggestion. 

1. Can you change the name to is_protected_pr_title, as the other one people may confuse that it always send a PR.
2. Can you put the doc update to another PR as single one.

Sorry I just realized that I haven't put a contributors guideline will put it asap. But thank you so much for your  contribution

**Comment by MrChocolatine** [comment]
> * Can you change the name to is_protected_pr_title, as the other one people may confuse that it always send a PR.

Wouldn't that be a little bit to have an argument starting with `is_` being a string? I would expect, personally, and like the input `is_protected`, to be a `boolean`.

What about simply `protected_pr_title`?

> 2\. Can you put the doc update to another PR as single one.

Sure I will do that.

**Comment by akhilmhdh** [comment]
Oh yes. Thats a good point. What about pr_title_on_protected

**Comment by MrChocolatine** [comment]
> Oh yes. Thats a good point. What about pr_title_on_protected

Let's go with that yes.

I realised just after my suggestion `protected_pr_title` is wrong, it kind of implies the PR to be created is protected... Doesn't make any sense.

**Pull request merged**
