### PR TITLE
Fix null name, no capitalize & introduce eslint fix command

### PR DESCRIPTION
**Pull request by melroy89**
- Fallback to username in case the name is empty/null
- I actually removed the capitalized usage, since my name is already CORRECTly capitalized in GitHub itself, and your method is actually making it worse not better. For example my name is: "Melroy van den Berg". And **NOT**.. "Melroy Van Den Berg". So no need to manually capitalize it.
- Introduce a simple eslint auto-fix npm command (`npm run fix`)
- Also ran `npm run build` already for you 👍🏽 

Fixes: #60

### CODE REVIEW

**Comment by reinder** [comment]
Awesome, hope it gets merged soon :)

**Comment by akhilmhdh** [comment]
Ohh wow @melroy89 

I am a bit tired tonight and yes i was pretty busy with my other works I never had time to focus on this task.

Appreciate your efforts for fixing it. I'll review and hopefully release this tomorrow for sure.

**Comment by melroy89** [comment]
> Appreciate your efforts for fixing it. I'll review and hopefully release this tomorrow for sure.

Understood. Thanks in advance. Sleep well I would say :).

**Review by akhilmhdh — APPROVED** [review]

**Comment by akhilmhdh** [comment]
Hey @melroy89 it has been released under `v2.3.9`. Again thanking you for taking your time on this one.

**Comment by reinder** [comment]
Awesome 😎 thx!

**Pull request merged**
